### ISSUE TITLE
Unable to autowire MetricRegistry

### ISSUE THREAD

**Issue by dustinbarnes** [ryantenney/metrics-spring#120]
We have a very basic configuration class for metrics: 

    @Configuration
    @EnableMetrics(proxyTargetClass = true, exposeProxy = true)
    public class MetricsConfig extends MetricsConfigurerAdapter implements WebApplicationInitializer
    {
        @Override
        public void onStartup(ServletContext servletContext) {
            final MetricsServlet servlet = new MetricsServlet(getMetricRegistry());

            final ServletRegistration.Dynamic servletRegistration = servletContext
                    .addServlet("MetricsServlet", servlet);
            servletRegistration.setLoadOnStartup(1);
            servletRegistration.addMapping("/metrics");
        }
    }

However, whenever we try to inject the metric registry into another class, we get this exception: 

    Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.codahale.metrics.MetricRegistry] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1261)
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1009)
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:904)
    	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:527)

Now, if I add a @Bean method to the MetricsConfig like so: 

    @Override
    @Bean
    public MetricRegistry getMetricRegistry()
    {
        return super.getMetricRegistry();
    }

It fails with the same exception. It's like the autowire magic is trying to autowire the metricregistry before the metric registry bean is being picked up. Spring usually does a good job with this... Any ideas?

**Comment by ryantenney** [comment]
Have you tried using two separate classes, one extending MetricsConfigurerAdapter, and one implementing WebApplicationInitializer?  Best suggestion I can come up with.

**Comment by dustinbarnes** [comment]
I did something similar. I got rid of that class entirely, and put the \@EnableMetrics on our main class. I just created a spring endpoint to expose the metrics. The real trouble is that the MetricRegistry wasn't initialized when initializing MetricServlet. 

Thanks for the reply.
