### ISSUE TITLE
Regression in 3.1.1

### ISSUE THREAD

**Issue by davidkarlsen** [ryantenney/metrics-spring#126]
This worked fine in 3.1.0:

```
@Timed
    @ExceptionMetered
    @Counted
    public Object myMethod()

```

Now with 3.1.1 I get:

```
es/com/edb/fs/tac/jfr/srv/service/account/CorsAccountServiceImpl.class]: Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: com.edb.fs.tac.jfr.srv.service.account.CorsAccountServiceImpl.listAccounts is already used for a different type of metric
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:133)
        at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:60)
        at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:109)
        at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:261)
        at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68)
        at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86)
        at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:72)
        at com.excilys.ebi.spring.dbunit.test.RollbackTransactionalDataSetTestExecutionListener.beforeTestClass(RollbackTransactionalDataSetTestExecutionListener.java:44)
        at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:179)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.IllegalArgumentException: com.edb.fs.tac.jfr.srv.service.account.CorsAccountServiceImpl.listAccounts is already used for a different type of metric
        at com.codahale.metrics.MetricRegistry.getOrAdd(MetricRegistry.java:325)
        at com.codahale.metrics.MetricRegistry.counter(MetricRegistry.java:115)
        at com.ryantenney.metrics.spring.CountedMethodInterceptor.buildMetric(CountedMethodInterceptor.java:57)
        at com.ryantenney.metrics.spring.CountedMethodInterceptor.buildMetric(CountedMethodInterceptor.java:32)
        at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.doWith(AbstractMetricMethodInterceptor.java:72)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:495)
        at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.<init>(AbstractMetricMethodInterceptor.java:52)
        at com.ryantenney.metrics.spring.CountedMethodInterceptor.<init>(CountedMethodInterceptor.java:39)
        at com.ryantenney.metrics.spring.CountedMethodInterceptor$1.getAdvice(CountedMethodInterceptor.java:69)
        at com.ryantenney.metrics.spring.AdvisingBeanPostProcessor.postProcessAfterInitialization(AdvisingBeanPostProcessor.java:62)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAut

**Comment by ryantenney** [comment]
Is that annotation `com.ryantenney.metrics.spring.annotation.Counted` or `com.codahale.metrics.annotation.Counted`? metrics-spring didn't scan for the latter until 3.1.1. You can fix this by setting the name on counted: `@Counted(name = "myMethod.count")`. You'll also find you get the same error if you have both `@Metered` and `@Timed` on a method without specifying a name.

**Comment by davidkarlsen** [comment]
It's com.codahale.metrics.annotation.Counted.
Wouldn't some naming strategy be favourable (generating a default name from the reflected Method) so you don't have to type them in all the time?

**Comment by ryantenney** [comment]
A name is generated, based on these rules:

For method `myMethod` in class `com.foo.Test`:

Annotation | Strategy | Metric Name
--- | --- | ---
`@Counted` (no attributes) | class name + method name | "com.foo.Test.myMethod"
`@Counted(name = "explicitName")` | class name + name attribute | "com.foo.Test.explicitName"
`@Counted(name = "explicitName", absolute = true)` | name attribute | "explicitName"

The exception to this rule is `@ExceptionMetered` which appends ".exceptions" to the method name when the `name` attribute isn't provided.

We could do the same for Counted, but we don't, because a Counter has one attribute `count`. Most reporters append the attribute name to the metric name, so we'd end up with `com.foo.Test.myMethod.count.count`.
