### ISSUE TITLE
 java.io.NotSerializableException: com.ryantenney.metrics.spring.CountedMethodInterceptor

### ISSUE THREAD

**Issue by mmoayyed** [ryantenney/metrics-spring#143]
```
03-Oct-2015 02:56:39.125 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [cas] in context with path [/cas] threw exception [Request processing failed; nested exception is org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'viewLoginForm' of flow 'login'] with root cause
 java.io.NotSerializableException: com.ryantenney.metrics.spring.CountedMethodInterceptor
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
```

**Comment by ryantenney** [comment]
I'd appreciate some details besides a stack trace. Does this describe your issue? https://stackoverflow.com/questions/14487843/notserializableexception-in-jsf-when-using-spring-aop

**Comment by mmoayyed** [comment]
Hi Ryan,
As much as I can tell, I have an application that uses Spring webflow. I have an object that is put inside a webflow scope that is causing this problem to appear. The object that is in the webflow scope has various methods that are decorated with Counted and Metered. Objects in the flow are required to be serializable. Apparently, this class here isnt. Does that make sense?

**Comment by ryantenney** [comment]
That makes sense, thanks for clarifying.  It hadn't occurred to me that AOP interceptors would also need to be serializable.  I'll try to look into it.

**Comment by mmoayyed** [comment]
Thanks.

**Comment by ryantenney** [comment]
I attempted to resolve this but didn't get anywhere with it. The MetricRegistry isn't serializable and I was having trouble figuring out how to get retrieve it when the interceptor is deserialized. At this point I don't know if this is resolvable without major rework.
