### ISSUE TITLE
Conflict with Spring Configuration @EnableRetry

### ISSUE THREAD

**Issue by brendangreene** [ryantenney/metrics-spring#162]
I'm using the the metrics project and today tried to enable retryable annotations for some integration work I'm doing. Any one else experience this? The app fails with the following:

Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy91 cannot be cast to com.codahale.metrics.MetricRegistry
	at com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration$$EnhancerBySpringCGLIB$$c13beb38.getMetricRegistry(<generated>)
	at com.ryantenney.metrics.spring.config.annotation.MetricsConfigurationSupport.exceptionMeteredAnnotationBeanPostProcessor(MetricsConfigurationSupport.java:64)
	at com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration$$EnhancerBySpringCGLIB$$c13beb38.CGLIB$exceptionMeteredAnnotationBeanPostProcessor$5(<generated>)
	at com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration$$EnhancerBySpringCGLIB$$c13beb38$$FastClassBySpringCGLIB$$b6480302.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration$$EnhancerBySpringCGLIB$$c13beb38.exceptionMeteredAnnotationBeanPostProcessor(<generated>)
	at com.ryantenney.metrics.spring.config.annotation.MetricsConfigurationSupport$$FastClassBySpringCGLIB$$1e5e739b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at com.ryantenney.metrics.spring.config.annotation.DelegatingMetricsConfiguration$$EnhancerBySpringCGLIB$$c927a4cb.exceptionMeteredAnnotationBeanPostProcessor(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 16 more

**Comment by brendangreene** [comment]
Upgraded to the latest Spring Retry and the issue is not occurring.

<dependency>
	<groupId>org.springframework.retry</groupId>
	<artifactId>spring-retry</artifactId>
	<version>1.1.2.RELEASE</version>
</dependency>
